### ISSUE TITLE
这个怎么使用

### ISSUE THREAD

**Issue by mejinke** [ppninja/wechat-speex-declib#1]
不会C，请教这个怎么使用，目前在做微信的speex转码的需求。。

**Comment by acenqiu** [comment]
bin目录下的`speex_decode`是一个编译好的可执行文件，在linux下可以直接运行。

```shell
speex_decode input output
```

如果要在其他平台下使用，可以直接编译。源文件中已经包含了`Makefile`，可以在网上了解下怎么通过它来编译。

**Comment by mejinke** [comment]
好的，已搞了，谢谢！
